### PR TITLE
New topic features

### PR DESCRIPTION
**Pull request by mauricionr**
Hey there, here is some new features, remove topics and add topics

Thanks

### CODE REVIEW

**Comment by oscarrenalias** [comment]
It looks like the Travis CI build failed, can you have a look? It seems that it's some basic style issues.

**Comment by mauricionr** [comment]
I forgot some semicolon, i'm fixing it

thanks!

**Comment by mauricionr** [comment]
Now looks like every thing ok!

**Comment by oscarrenalias** [comment]
On a somewhat related note, would you be interested in taking over the maintenance of this library? As you may have noticed, I haven't added new features for a long time since I'm not using it anymore; if you are, I'd be happy to transfer the project to you.

**Comment by mauricionr** [comment]
Ow really nice, you can transfer to me, I'm using a lot feauture on them
and I will need to create more features.

Thanks a lot!

**Comment by oscarrenalias** [comment]
Would you like me to do it right away? It seems that it's only a matter of a click of a button in Github.

Are you planning to publish new versions of the library to Npm? If so, I'll look into transferring project ownership there too.

**Comment by oscarrenalias** [comment]
Oh, and thanks for volunteering to take over :smile:

**Comment by mauricionr** [comment]
Any time do you want,

Yes my focus is to publish new versions on github and npm.

Thanks!

**Comment by mauricionr** [comment]
Thank you too.

**Comment by mauricionr** [comment]
@oscarrenalias Here is my user on npm [mauricionr](https://www.npmjs.com/~mauricionr)

**Comment by oscarrenalias** [comment]
It seems you already have a fork of the repo so I can't transfer it to you. I think that you could either keep your repo as it is (and I delete this one), or you delete it and I do a formal transfer via Github. Let me know which way you prefer.

I'm also trying to figure out how to transfer the project in npmjs, so far I can't see it...

**Comment by oscarrenalias** [comment]
I managed to figure out ownership in npmjs.com:

```
oscar.renalias [jobs=0]:yammer-rest-api-client-node (master)$ npm owner rm oscarrenalias
- oscarrenalias (yammer-rest-api-client)
oscar.renalias [jobs=0]:yammer-rest-api-client-node (master)$ npm owner ls
mauricionr <mauricioskateboard@gmail.com>
```
For some reason the user interface doesn't reflect the updates yet (https://www.npmjs.com/package/yammer-rest-api-client) but I hope it's just a matter of caching.

**Comment by mauricionr** [comment]
I will delete mine, and you can transfer this one.
I guess it's just cache.

**Comment by mauricionr** [comment]
Done, I've already delete mine!

**Comment by mauricionr** [comment]
I've checked it out my npmjs profile and the transfer it's ok.

image

:smiley:

**Comment by oscarrenalias** [comment]
Transfer has been requested, you probably need to approve it now!

**Comment by mauricionr** [comment]
I'm trying to find this request but i couldn't, do you know?

**Comment by oscarrenalias** [comment]
I think the transfer wasn't completed, but it seems that you already have a fork.

Maybe we should just leave it at that. Just work on your fork and I'll put a notice in the README in mine that development continues your fork!

**Comment by mauricionr** [comment]
No problem, i will stay with mine,

Thanks!

-----Original Message-----

**Pull request merged**
